### ISSUE TITLE
Link Problems :(

### ISSUE THREAD

**Issue by amaltariq** [esorey/CS143-Network-Simulator#21]
1. (RESOLVED) When logging buffer occupancy, do we care about the link in the forward AND backward direction? Currently we considering buffer occupancy separately.

2. (RESOLVED) Also: Link capacity should be halved right? Since our links are unidirectional. Currently if a link is set up to have a buffer capacity of 64, each direction will be 64, though I think it should be 32 (and we asked TAs about this too, I think they said 32 each direction). 

3. (RESOLVED) And we lose LINK IDs that we should log in log_buffer_occupancy (links that are clearly used aren't represented in the analytics dictionary for buffer occupancy :()

**Comment by amaltariq** [comment]
3 was resolved. Basically, when a packet went straight through the link (without sitting in buffer), we weren't logging that the buffer was empty, so I added something to log that

**Comment by esorey** [comment]
We now track the buffer occupancy for both directions of a link. One-way links also use only half the occupancy of the entire link.
