### ISSUE TITLE
Link Buffer Implementation Issue

### ISSUE THREAD

**Issue by amaltariq** [esorey/CS143-Network-Simulator#7]
The link is not exactly implemented correctly because it's size is limited by number of elements rather than packet size.
But links can hold more ACK packets than DATA packets for example since ACK packets are smaller and the link buffer capacity is limited by bytes not by number of packets. This implementation needs to be modified to account for that (perhaps use a counter to determine if the maximum size is reached?).

**Comment by schen5050** [comment]
This would really only affect dropped packets right? So we just wouldn't be able to use .full() on the buffer and need to change that to a counter

**Comment by schen5050** [comment]
Changed to be a counter that is full when the counter + packet size is greater than capacity
