### ISSUE TITLE
Analytics Things to Think About

### ISSUE THREAD

**Issue by amaltariq** [esorey/CS143-Network-Simulator#8]
We need to think a little more deeply about how analytics are implemented. 

For example, for log_flow_rate(linkID, numBytes, currTime, prevTime), which tries to calculate the flow over a link, how do we get prevTime and currTime?

We want to include the time the packet waited in the buffer at that link, so we need to do something like recording the time the packet was enqueued in a link buffer, and then also recording the time the packet reaches the destination at the end of the link. This wouldn't be too hard to implement, but we need our structure (in analytics class) to be able to contain link ID as well as some form of the packet ID (but remember different flows might have identical packet IDs so this might also be a problem), in order to record when it entered the link buffer and when it received it's destination on that link.

**Comment by schen5050** [comment]
Instead of link ID wouldn't we just get flow ID? Which is in the data packet already
